language: go

sudo: required
go:
  - 1.13.x
  - 1.14.x
services:
  - mysql
  - redis
  - mongodb
env:
  - GO111MODULE=on
before_install:
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    sudo dpkg -i erlang-solutions_1.0_all.deb
    sudo rm -rf erlang-solutions_1.0_all.deb
    sudo apt-get update
    sudo apt-get install erlang
    wget -O - "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | sudo apt-key add -
    curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
    sudo apt-get install rabbitmq-server
  -./rabbitmq
  - go mod tidy
  - mysql -e 'CREATE DATABASE IF NOT EXISTS beetest;'
script:
  - go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic