language: go

sudo: required
go:
  - 1.13.x
  - 1.14.x
services:
  - mysql
  - redis
  - mongodb
  - docker
env:
  - GO111MODULE=on
before_install:
  - docker run -d --hostname my-rabbit --name rabbit -p 15672:15672 -p 5672:5672 rabbitmq:management
  - go mod tidy
  - mysql -e 'CREATE DATABASE IF NOT EXISTS beetest;'
script:
  - go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic